TrajectoryPlannerROS:
  holonomic_robot: false
  controller_frequency: 20
  max_vel_x: 0.35
  min_vel_x: 0.15
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  sim_time: 1.0
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: true
  pdist_scale: 2
  
make_plan_add_unreachable_goal: false
make_plan_clear_costmap: false
