TrajectoryPlannerROS:
  holonomic_robot: false
  controller_frequency: 10
  max_vel_x: 0.35
  min_vel_x: 0.15
  min_in_place_rotational_vel: 0.8
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true
