scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser
    min_x: -0.150
    max_x: 0.150
    min_y: -0.100
    max_y: 0.100
    min_z: -1.000
    max_z: 1.000
