footprint: [[0.16, 0.16], [0.16, -0.16], [-0.16, -0.16], [-0.16, 0.16]]
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: laser
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true

